### ISSUE TITLE
Can the latest version be published to crates.io?

### ISSUE THREAD

**Issue by Samathingamajig** [nexxeln/license-generator#10]
A couple days ago I remembered this tool existed, so I used it, only to see that 2022 was the default for the current year. I came to this repo just now to submit a PR to fix that, but turns out #6 did that.

I just performed a clean install to double-check that the issue was still occurring, and it is.

<img width="581" alt="image" src="https://github.com/nexxeln/license-generator/assets/29130894/32c9f5de-251e-4c0e-b41f-46e894b55563">

One other minor change is that this line
https://github.com/nexxeln/license-generator/blob/70854230ef393b9ad0552f811dc16e4da3e8eeee/src/helpers.rs#L108
should probably be replaced with `Local::Now().year()`, just to avoid the edge case of New Year's Eve/Day.

**Comment by nexxeln** [comment]
done, thank you
